### ISSUE TITLE
Building and Hosting documentation on readthedocs

### ISSUE THREAD

**Issue by andersy005** [NCAR/PyConform#62]
@sherimickelson  and @kmpaul, I made [little changes](https://github.com/andersy005/PyConform/tree/devel/docs) in the structure of the docs directory to automatically build and deploy docs. After making the changes, I set up a Repository webhook on my Github so that [Read the Docs](https://readthedocs.org/) can be able to access the Repo content. So far, my attempt has been successful. The docs are hosted at http://pyconform.readthedocs.io/en/latest/.

Let me know if this is something you would want to add the project structure and I will create a pull request.

**Comment by kmpaul** [comment]
It seems this link is broken.  I assume that the RTD deployment is no longer worker.  It seems to work well from GitHub Pages, though, so maybe we should close this?
