### ISSUE TITLE
PyConform User’s Manual is really PyReshaper User's Manual

### ISSUE THREAD

**Issue by mnichol3** [NCAR/PyConform#95]
The user's manual in `docs/manual.html` goes into great detail about setting up and running PyReshaper, but doesn't mention how to use PyConform at all.

**Comment by kmpaul** [comment]
@mnichol3 Good catch.  That is fixed.  (Namely, I've removed the `manual.html`.)

I believe the documentation is now "consistent," but it is very incomplete.  And, unfortunately, I suspect that it will remain incomplete without additional help from external contributors.  This tool is not really ready for public use, except for those people extremely motived to do so.  Sadly, we just cannot support its use outside of NCAR's internal CMIP6 workflow.

That said, we are happy to take external contributions (in the form of PRs) to fix bugs, add/update documentation, develop use cases/examples, etc.  But, going into the future, we highly recommend looking into [Xarray](https://xarray.pydata.org).  Much of what we have implemented with PyConform can be done with Xarray, and I suspect that in 6-months time, all of what we have implemented with PyConform will be reproducible with Xarray.
